<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // ['code' => "AF", 'icon' => "afghanistan.svg", 'name' => "Afghanistan"],
            // ['code' => "AX", 'icon' => "aland-islands.svg", 'name' => "Aland Islands"],
            // ['code' => "AL", 'icon' => "albania.svg", 'name' => "Albania"],
            // ['code' => "DZ", 'icon' => "algeria.svg", 'name' => "Algeria"],
            // ['code' => "AS", 'icon' => "american-samoa.svg", 'name' => "American Samoa"],
            // ['code' => "AD", 'icon' => "andorra.svg", 'name' => "Andorra"],
            // ['code' => "AO", 'icon' => "angola.svg", 'name' => "Angola"],
            // ['code' => "AI", 'icon' => "anguilla.svg", 'name' => "Anguilla"],
            // ['code' => "AG", 'icon' => "antigua-and-barbuda.svg", 'name' => "Antigua and Barbuda"],
            // ['code' => "AR", 'icon' => "argentina.svg", 'name' => "Argentina"],
            // ['code' => "AM", 'icon' => "armenia.svg", 'name' => "Armenia"],
            // ['code' => "AW", 'icon' => "aruba.svg", 'name' => "Aruba"],
            // ['code' => "AU", 'icon' => "australia.svg", 'name' => "Australia"],
            // ['code' => "AT", 'icon' => "austria.svg", 'name' => "Austria"],
            // ['code' => "AZ", 'icon' => "azerbaijan.svg", 'name' => "Azerbaijan"],
            // ['code' => "BS", 'icon' => "bahamas.svg", 'name' => "Bahamas"],
            // ['code' => "BH", 'icon' => "bahrain.svg", 'name' => "Bahrain"],
            // ['code' => "BD", 'icon' => "bangladesh.svg", 'name' => "Bangladesh"],
            // ['code' => "BB", 'icon' => "barbados.svg", 'name' => "Barbados"],
            // ['code' => "BY", 'icon' => "belarus.svg", 'name' => "Belarus"],
            // ['code' => "BE", 'icon' => "belgium.svg", 'name' => "Belgium"],
            // ['code' => "BZ", 'icon' => "belize.svg", 'name' => "Belize"],
            // ['code' => "BJ", 'icon' => "benin.svg", 'name' => "Benin"],
            // ['code' => "BM", 'icon' => "bermuda.svg", 'name' => "Bermuda"],
            // ['code' => "BT", 'icon' => "bhutan.svg", 'name' => "Bhutan"],
            // ['code' => "BO", 'icon' => "bolivia.svg", 'name' => "Bolivia, Plurinational State of"],
            // ['code' => "BQ", 'icon' => "bonaire.svg", 'name' => "Bonaire, Sint Eustatius and Saba"],
            // ['code' => "BA", 'icon' => "bosnia-and-herzegovina.svg", 'name' => "Bosnia and Herzegovina"],
            // ['code' => "BW", 'icon' => "botswana.svg", 'name' => "Botswana"],
            // ['code' => "BR", 'icon' => "brazil.svg", 'name' => "Brazil"],
            // ['code' => "IO", 'icon' => "british-indian-ocean-territory.svg", 'name' => "British Indian Ocean Territory"],
            // ['code' => "BN", 'icon' => "brunei.svg", 'name' => "Brunei Darussalam"],
            // ['code' => "BG", 'icon' => "bulgaria.svg", 'name' => "Bulgaria"],
            // ['code' => "BF", 'icon' => "burkina-faso.svg", 'name' => "Burkina Faso"],
            // ['code' => "BI", 'icon' => "burundi.svg", 'name' => "Burundi"],
            // ['code' => "KH", 'icon' => "cambodia.svg", 'name' => "Cambodia"],
            // ['code' => "CM", 'icon' => "cameroon.svg", 'name' => "Cameroon"],
            // ['code' => "CA", 'icon' => "canada.svg", 'name' => "Canada"],
            // ['code' => "CV", 'icon' => "cape-verde.svg", 'name' => "Cape Verde"],
            // ['code' => "KY", 'icon' => "cayman-islands.svg", 'name' => "Cayman Islands"],
            // ['code' => "CF", 'icon' => "central-african-republic.svg", 'name' => "Central African Republic"],
            // ['code' => "TD", 'icon' => "chad.svg", 'name' => "Chad"],
            // ['code' => "CL", 'icon' => "chile.svg", 'name' => "Chile"],
            // ['code' => "CN", 'icon' => "china.svg", 'name' => "China"],
            // ['code' => "CX", 'icon' => "christmas-island.svg", 'name' => "Christmas Island"],
            // ['code' => "CC", 'icon' => "cocos-island.svg", 'name' => "Cocos (Keeling) Islands"],
            // ['code' => "CO", 'icon' => "colombia.svg", 'name' => "Colombia"],
            // ['code' => "KM", 'icon' => "comoros.svg", 'name' => "Comoros"],
            // ['code' => "CK", 'icon' => "cook-islands.svg", 'name' => "Cook Islands"],
            // ['code' => "CR", 'icon' => "costa-rica.svg", 'name' => "Costa Rica"],
            // ['code' => "CI", 'icon' => "ivory-coast.svg", 'name' => "Côte d'Ivoire"],
            // ['code' => "HR", 'icon' => "croatia.svg", 'name' => "Croatia"],
            // ['code' => "CU", 'icon' => "cuba.svg", 'name' => "Cuba"],
            // ['code' => "CW", 'icon' => "curacao.svg", 'name' => "Curaçao"],
            // ['code' => "CZ", 'icon' => "czech-republic.svg", 'name' => "Czech Republic"],
            // ['code' => "DK", 'icon' => "denmark.svg", 'name' => "Denmark"],
            // ['code' => "DJ", 'icon' => "djibouti.svg", 'name' => "Djibouti"],
            // ['code' => "DM", 'icon' => "dominica.svg", 'name' => "Dominica"],
            // ['code' => "DO", 'icon' => "dominican-republic.svg", 'name' => "Dominican Republic"],
            // ['code' => "EC", 'icon' => "ecuador.svg", 'name' => "Ecuador"],
            // ['code' => "EG", 'icon' => "egypt.svg", 'name' => "Egypt"],
            // ['code' => "SV", 'icon' => "el-salvador.svg", 'name' => "El Salvador"],
            // ['code' => "GQ", 'icon' => "equatorial-guinea.svg", 'name' => "Equatorial Guinea"],
            // ['code' => "ER", 'icon' => "eritrea.svg", 'name' => "Eritrea"],
            // ['code' => "EE", 'icon' => "estonia.svg", 'name' => "Estonia"],
            // ['code' => "ET", 'icon' => "ethiopia.svg", 'name' => "Ethiopia"],
            // ['code' => "FK", 'icon' => "falkland-islands.svg", 'name' => "Falkland Islands (Malvinas)"],
            // ['code' => "FJ", 'icon' => "fiji.svg", 'name' => "Fiji"],
            // ['code' => "FI", 'icon' => "finland.svg", 'name' => "Finland"],
            // ['code' => "FR", 'icon' => "france.svg", 'name' => "France"],
            // ['code' => "PF", 'icon' => "french-polynesia.svg", 'name' => "French Polynesia"],
            // ['code' => "GA", 'icon' => "gabon.svg", 'name' => "Gabon"],
            // ['code' => "GM", 'icon' => "gambia.svg", 'name' => "Gambia"],
            // ['code' => "GE", 'icon' => "georgia.svg", 'name' => "Georgia"],
            // ['code' => "DE", 'icon' => "germany.svg", 'name' => "Germany"],
            // ['code' => "GH", 'icon' => "ghana.svg", 'name' => "Ghana"],
            // ['code' => "GI", 'icon' => "gibraltar.svg", 'name' => "Gibraltar"],
            // ['code' => "GR", 'icon' => "greece.svg", 'name' => "Greece"],
            // ['code' => "GL", 'icon' => "greenland.svg", 'name' => "Greenland"],
            // ['code' => "GD", 'icon' => "grenada.svg", 'name' => "Grenada"],
            // ['code' => "GU", 'icon' => "guam.svg", 'name' => "Guam"],
            // ['code' => "GT", 'icon' => "guatemala.svg", 'name' => "Guatemala"],
            // ['code' => "GG", 'icon' => "guernsey.svg", 'name' => "Guernsey"],
            // ['code' => "GN", 'icon' => "guinea.svg", 'name' => "Guinea"],
            // ['code' => "GW", 'icon' => "guinea-bissau.svg", 'name' => "Guinea-Bissau"],
            // ['code' => "HT", 'icon' => "haiti.svg", 'name' => "Haiti"],
            // ['code' => "VA", 'icon' => "vatican-city.svg", 'name' => "Holy See (Vatican City State)"],
            // ['code' => "HN", 'icon' => "honduras.svg", 'name' => "Honduras"],
            // ['code' => "HK", 'icon' => "hong-kong.svg", 'name' => "Hong Kong"],
            // ['code' => "HU", 'icon' => "hungary.svg", 'name' => "Hungary"],
            // ['code' => "IS", 'icon' => "iceland.svg", 'name' => "Iceland"],
            // ['code' => "IN", 'icon' => "india.svg", 'name' => "India"],
            // ['code' => "ID", 'icon' => "indonesia.svg", 'name' => "Indonesia"],
            // ['code' => "IR", 'icon' => "iran.svg", 'name' => "Iran, Islamic Republic of"],
            // ['code' => "IQ", 'icon' => "iraq.svg", 'name' => "Iraq"],
            // ['code' => "IE", 'icon' => "ireland.svg", 'name' => "Ireland"],
            // ['code' => "IM", 'icon' => "isle-of-man.svg", 'name' => "Isle of Man"],
            ['code' => "PS", 'icon' => "palestine.svg", 'name' => "Palestine"],
            ['code' => "IL", 'icon' => "israel.svg", 'name' => "Israel"],
            // ['code' => "IT", 'icon' => "italy.svg", 'name' => "Italy"],
            // ['code' => "JM", 'icon' => "jamaica.svg", 'name' => "Jamaica"],
            // ['code' => "JP", 'icon' => "japan.svg", 'name' => "Japan"],
            // ['code' => "JE", 'icon' => "jersey.svg", 'name' => "Jersey"],
            // ['code' => "JO", 'icon' => "jordan.svg", 'name' => "Jordan"],
            // ['code' => "KZ", 'icon' => "kazakhstan.svg", 'name' => "Kazakhstan"],
            // ['code' => "KE", 'icon' => "kenya.svg", 'name' => "Kenya"],
            // ['code' => "KI", 'icon' => "kiribati.svg", 'name' => "Kiribati"],
            // ['code' => "KP", 'icon' => "north-korea.svg", 'name' => "Korea, Democratic People's Republic of"],
            // ['code' => "KW", 'icon' => "kuwait.svg", 'name' => "Kuwait"],
            // ['code' => "KG", 'icon' => "kyrgyzstan.svg", 'name' => "Kyrgyzstan"],
            // ['code' => "LA", 'icon' => "laos.svg", 'name' => "Lao People's Democratic Republic"],
            // ['code' => "LV", 'icon' => "latvia.svg", 'name' => "Latvia"],
            // ['code' => "LB", 'icon' => "lebanon.svg", 'name' => "Lebanon"],
            // ['code' => "LS", 'icon' => "lesotho.svg", 'name' => "Lesotho"],
            // ['code' => "LR", 'icon' => "liberia.svg", 'name' => "Liberia"],
            // ['code' => "LY", 'icon' => "libya.svg", 'name' => "Libya"],
            // ['code' => "LI", 'icon' => "liechtenstein.svg", 'name' => "Liechtenstein"],
            // ['code' => "LT", 'icon' => "lithuania.svg", 'name' => "Lithuania"],
            // ['code' => "LU", 'icon' => "luxembourg.svg", 'name' => "Luxembourg"],
            // ['code' => "MO", 'icon' => "macao.svg", 'name' => "Macao"],
            // ['code' => "MG", 'icon' => "madagascar.svg", 'name' => "Madagascar"],
            // ['code' => "MW", 'icon' => "malawi.svg", 'name' => "Malawi"],
            // ['code' => "MY", 'icon' => "malaysia.svg", 'name' => "Malaysia"],
            // ['code' => "MV", 'icon' => "maldives.svg", 'name' => "Maldives"],
            // ['code' => "ML", 'icon' => "mali.svg", 'name' => "Mali"],
            // ['code' => "MT", 'icon' => "malta.svg", 'name' => "Malta"],
            // ['code' => "MH", 'icon' => "marshall-island.svg", 'name' => "Marshall Islands"],
            // ['code' => "MQ", 'icon' => "martinique.svg", 'name' => "Martinique"],
            // ['code' => "MR", 'icon' => "mauritania.svg", 'name' => "Mauritania"],
            // ['code' => "MU", 'icon' => "mauritius.svg", 'name' => "Mauritius"],
            // ['code' => "MX", 'icon' => "mexico.svg", 'name' => "Mexico"],
            // ['code' => "FM", 'icon' => "micronesia.svg", 'name' => "Micronesia, Federated States of"],
            // ['code' => "MD", 'icon' => "moldova.svg", 'name' => "Moldova, Republic of"],
            // ['code' => "MC", 'icon' => "monaco.svg", 'name' => "Monaco"],
            // ['code' => "MN", 'icon' => "mongolia.svg", 'name' => "Mongolia"],
            // ['code' => "ME", 'icon' => "montenegro.svg", 'name' => "Montenegro"],
            // ['code' => "MS", 'icon' => "montserrat.svg", 'name' => "Montserrat"],
            // ['code' => "MA", 'icon' => "morocco.svg", 'name' => "Morocco"],
            // ['code' => "MZ", 'icon' => "mozambique.svg", 'name' => "Mozambique"],
            // ['code' => "MM", 'icon' => "myanmar.svg", 'name' => "Myanmar"],
            // ['code' => "NA", 'icon' => "namibia.svg", 'name' => "Namibia"],
            // ['code' => "NR", 'icon' => "nauru.svg", 'name' => "Nauru"],
            // ['code' => "NP", 'icon' => "nepal.svg", 'name' => "Nepal"],
            // ['code' => "NL", 'icon' => "netherlands.svg", 'name' => "Netherlands"],
            // ['code' => "NZ", 'icon' => "new-zealand.svg", 'name' => "New Zealand"],
            // ['code' => "NI", 'icon' => "nicaragua.svg", 'name' => "Nicaragua"],
            // ['code' => "NE", 'icon' => "niger.svg", 'name' => "Niger"],
            // ['code' => "NG", 'icon' => "nigeria.svg", 'name' => "Nigeria"],
            // ['code' => "NU", 'icon' => "niue.svg", 'name' => "Niue"],
            // ['code' => "NF", 'icon' => "norfolk-island.svg", 'name' => "Norfolk Island"],
            // ['code' => "MP", 'icon' => "northern-mariana-islands.svg", 'name' => "Northern Mariana Islands"],
            // ['code' => "NO", 'icon' => "norway.svg", 'name' => "Norway"],
            // ['code' => "OM", 'icon' => "oman.svg", 'name' => "Oman"],
            // ['code' => "PK", 'icon' => "pakistan.svg", 'name' => "Pakistan"],
            // ['code' => "PW", 'icon' => "palau.svg", 'name' => "Palau"],
            // ['code' => "PA", 'icon' => "panama.svg", 'name' => "Panama"],
            // ['code' => "PG", 'icon' => "papua-new-guinea.svg", 'name' => "Papua New Guinea"],
            // ['code' => "PY", 'icon' => "paraguay.svg", 'name' => "Paraguay"],
            // ['code' => "PE", 'icon' => "peru.svg", 'name' => "Peru"],
            // ['code' => "PH", 'icon' => "philippines.svg", 'name' => "Philippines"],
            // ['code' => "PL", 'icon' => "poland.svg", 'name' => "Poland"],
            // ['code' => "PT", 'icon' => "portugal.svg", 'name' => "Portugal"],
            // ['code' => "PR", 'icon' => "puerto-rico.svg", 'name' => "Puerto Rico"],
            // ['code' => "QA", 'icon' => "qatar.svg", 'name' => "Qatar"],
            // ['code' => "RO", 'icon' => "romania.svg", 'name' => "Romania"],
            // ['code' => "RU", 'icon' => "russia.svg", 'name' => "Russian Federation"],
            // ['code' => "RW", 'icon' => "rwanda.svg", 'name' => "Rwanda"],
            // ['code' => "BL", 'icon' => "st-barts.svg", 'name' => "Saint Barthélemy"],
            // ['code' => "KN", 'icon' => "saint-kitts-and-nevis.svg", 'name' => "Saint Kitts and Nevis"],
            // ['code' => "LC", 'icon' => "st-lucia.svg", 'name' => "Saint Lucia"],
            // ['code' => "MF", 'icon' => "sint-maarten.svg", 'name' => "Saint Martin (French part)"],
            // ['code' => "VC", 'icon' => "st-vincent-and-the-grenadines.svg", 'name' => "Saint Vincent and the Grenadines"],
            // ['code' => "WS", 'icon' => "samoa.svg", 'name' => "Samoa"],
            // ['code' => "SM", 'icon' => "san-marino.svg", 'name' => "San Marino"],
            // ['code' => "ST", 'icon' => "sao-tome-and-prince.svg", 'name' => "Sao Tome and Principe"],
            // ['code' => "SA", 'icon' => "saudi-arabia.svg", 'name' => "Saudi Arabia"],
            // ['code' => "SN", 'icon' => "senegal.svg", 'name' => "Senegal"],
            // ['code' => "RS", 'icon' => "serbia.svg", 'name' => "Serbia"],
            // ['code' => "SC", 'icon' => "seychelles.svg", 'name' => "Seychelles"],
            // ['code' => "SL", 'icon' => "sierra-leone.svg", 'name' => "Sierra Leone"],
            // ['code' => "SG", 'icon' => "singapore.svg", 'name' => "Singapore"],
            // ['code' => "SX", 'icon' => "sint-maarten.svg", 'name' => "Sint Maarten (Dutch part)"],
            // ['code' => "SK", 'icon' => "slovakia.svg", 'name' => "Slovakia"],
            // ['code' => "SI", 'icon' => "slovenia.svg", 'name' => "Slovenia"],
            // ['code' => "SB", 'icon' => "solomon-islands.svg", 'name' => "Solomon Islands"],
            // ['code' => "SO", 'icon' => "somalia.svg", 'name' => "Somalia"],
            // ['code' => "ZA", 'icon' => "south-africa.svg", 'name' => "South Africa"],
            // ['code' => "KR", 'icon' => "south-korea.svg", 'name' => "South Korea"],
            // ['code' => "SS", 'icon' => "south-sudan.svg", 'name' => "South Sudan"],
            // ['code' => "ES", 'icon' => "spain.svg", 'name' => "Spain"],
            // ['code' => "LK", 'icon' => "sri-lanka.svg", 'name' => "Sri Lanka"],
            // ['code' => "SD", 'icon' => "sudan.svg", 'name' => "Sudan"],
            // ['code' => "SR", 'icon' => "suriname.svg", 'name' => "Suriname"],
            // ['code' => "SZ", 'icon' => "swaziland.svg", 'name' => "Swaziland"],
            // ['code' => "SE", 'icon' => "sweden.svg", 'name' => "Sweden"],
            // ['code' => "CH", 'icon' => "switzerland.svg", 'name' => "Switzerland"],
            // ['code' => "SY", 'icon' => "syria.svg", 'name' => "Syrian Arab Republic"],
            // ['code' => "TW", 'icon' => "taiwan.svg", 'name' => "Taiwan, Province of China"],
            // ['code' => "TJ", 'icon' => "tajikistan.svg", 'name' => "Tajikistan"],
            // ['code' => "TZ", 'icon' => "tanzania.svg", 'name' => "Tanzania, United Republic of"],
            // ['code' => "TH", 'icon' => "thailand.svg", 'name' => "Thailand"],
            // ['code' => "TG", 'icon' => "togo.svg", 'name' => "Togo"],
            // ['code' => "TK", 'icon' => "tokelau.svg", 'name' => "Tokelau"],
            // ['code' => "TO", 'icon' => "tonga.svg", 'name' => "Tonga"],
            // ['code' => "TT", 'icon' => "trinidad-and-tobago.svg", 'name' => "Trinidad and Tobago"],
            // ['code' => "TN", 'icon' => "tunisia.svg", 'name' => "Tunisia"],
            // ['code' => "TR", 'icon' => "turkey.svg", 'name' => "Turkey"],
            // ['code' => "TM", 'icon' => "turkmenistan.svg", 'name' => "Turkmenistan"],
            // ['code' => "TC", 'icon' => "turks-and-caicos.svg", 'name' => "Turks and Caicos Islands"],
            // ['code' => "TV", 'icon' => "tuvalu.svg", 'name' => "Tuvalu"],
            // ['code' => "UG", 'icon' => "uganda.svg", 'name' => "Uganda"],
            // ['code' => "UA", 'icon' => "ukraine.svg", 'name' => "Ukraine"],
            // ['code' => "AE", 'icon' => "united-arab-emirates.svg", 'name' => "United Arab Emirates"],
            // ['code' => "GB", 'icon' => "united-kingdom.svg", 'name' => "United Kingdom"],
            // ['code' => "US", 'icon' => "united-states.svg", 'name' => "United States"],
            // ['code' => "UY", 'icon' => "uruguay.svg", 'name' => "Uruguay"],
            // ['code' => "UZ", 'icon' => "uzbekistan.svg", 'name' => "Uzbekistan"],
            // ['code' => "VU", 'icon' => "vanuatu.svg", 'name' => "Vanuatu"],
            // ['code' => "VE", 'icon' => "venezuela.svg", 'name' => "Venezuela, Bolivarian Republic of"],
            // ['code' => "VN", 'icon' => "vietnam.svg", 'name' => "Vietnam"],
            // ['code' => "VI", 'icon' => "virgin-islands.svg", 'name' => "Virgin Islands"],
            // ['code' => "YE", 'icon' => "yemen.svg", 'name' => "Yemen"],
            // ['code' => "ZM", 'icon' => "zambia.svg", 'name' => "Zambia"],
            // ['code' => "ZW", 'icon' => "zimbabwe.svg", 'name' => "Zimbabwe"],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['name' => $country['name'], 'code' => $country['code'], 'icon' => $country['icon']]);
        }
        $this->command->info('Countries added  successfully!');
    }
}
