<?php
return   [
    'Unparalleled facilities and features' => 'Unparalleled facilities and features',
    'A range of modern facilities designed to provide maximum comfort for residents' => 'A range of modern facilities designed to provide maximum comfort for residents',
    'Luxury of life begins here' => 'Luxury of life begins here',
    'Send' => 'Send',
    'Name' => 'Name',
    'Phone Number' => 'Phone Number',
    'Email' => 'Email',
    'Desired Apartment Size' => 'Desired Apartment Size',
    'Family Number' => 'Family Number',
    'Tower Design' => 'Tower Design',
    'Architectural brilliance and unmatched luxury' => 'Architectural brilliance and unmatched luxury',
    '18 floors in each tower combining modern architecture with high-end finishes' => '18 floors in each tower combining modern architecture with high-end finishes',
    'Each tower contains 3 apartments designed with practicality and comfort in mind' => 'Each tower contains 3 apartments designed with practicality and comfort in mind',
    'With large windows to maximise natural light and modern interiors.' => 'With large windows to maximise natural light and modern interiors.',
    'Advanced security system and spacious living areas that meet all residents aspirations' => 'Advanced security system and spacious living areas that meet all residents aspirations',
    'Lobbies designed in luxury hotel style, adding an atmosphere of elegance and comfort' => 'Lobbies designed in luxury hotel style, adding an atmosphere of elegance and comfort',
    'Multiple entrances ensuring easy access and security, with elevators equipped for furniture and heavy load transportation to facilitate movement within the towers' => 'Multiple entrances ensuring easy access and security, with elevators equipped for furniture and heavy load transportation to facilitate movement within the towers',
    'Parking lots equipped with charging stations for electric vehicles, storage spaces, and a central gas and electricity system' => 'Parking lots equipped with charging stations for electric vehicles, storage spaces, and a central gas and electricity system',
    'A Thriving Community for All Lifestyles' => 'A Thriving Community for All Lifestyles',
    'Choose Your Perfect Home' => 'Choose Your Perfect Home',
    'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                its
                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                its
                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                with the utmost comfort and quality.',
    'Apartment Styles' => 'Apartment Styles',
    'It provides residents with easy access to a range of essential services and amenities, including public transportation, schools, and shopping malls.' => 'It provides residents with easy access to a range of essential services and amenities, including public transportation, schools, and shopping malls.',
    'The location offers a tranquil environment surrounded by green spaces, making it an ideal place to live away from the noise of the city.' => 'The location offers a tranquil environment surrounded by green spaces, making it an ideal place to live away from the noise of the city.',
    'A thriving community for all lifestyles' => 'A thriving community for all lifestyles',
    'Elite Tower is not just a place to live' => 'Elite Tower is not just a place to live',
    'An integrated community offering spaces for socializing' => 'An integrated community offering spaces for socializing',
    'Family activities and relaxation' => 'Family activities and relaxation',
    'Towers designed to meet the needs of all family members' => 'Towers designed to meet the needs of all family members',
    'With diverse facilities catering to different interests' => 'With diverse facilities catering to different interests',
    'Including' => 'Including',
    'Retail spaces, children\'s play areas, and public gardens' => 'Retail spaces, children\'s play areas, and public gardens',
    'Image 1' => 'Image 1',
    'Image 4' => 'Image 4',
    'Image 2' => 'Image 2',
    'Image 5' => 'Image 5',
    'Image 3' => 'Image 3',
    'Image 6' => 'Image 6',  
  'Name is required' => 'Name is required',  
  'Name must be at least 3 characters' => 'Name must be at least 3 characters',  
  'Email is required' => 'Email is required',  
  'Please enter a valid email address' => 'Please enter a valid email address',  
  'Phone number is required' => 'Phone number is required',  
  'Please enter a valid phone number' => 'Please enter a valid phone number',  
  'Please select an apartment size' => 'Please select an apartment size',  
  'Family number is required' => 'Family number is required',  
  'Please enter a valid number' => 'Please enter a valid number',  
  'Sending...' => 'Sending...',  
  'Thank you! We will contact you shortly.' => 'Thank you! We will contact you shortly.',  
  'Failed to submit. Please try again.' => 'Failed to submit. Please try again.',  
  'An error occurred. Please try again.' => 'An error occurred. Please try again.',  
  'Lead created successfully! We will contact you shortly.' => 'Lead created successfully! We will contact you shortly.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                its
                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                its
                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                with the utmost comfort and quality.',  
  'Back to Apartments' => 'Back to Apartments',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                its
                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                its
                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                        its
                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                        its
                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                        its
                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                        its
                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                its
                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                its
                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                        its
                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                        its
                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                its
                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                its
                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                        its
                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                        its
                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        its
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                its
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                The spaces are spacious and offered at an affordable price, with a design that provides you
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with the utmost comfort and quality.',  
  'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from its proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way. The spaces are spacious and offered at an affordable price, with a design that provides you with the utmost comfort and quality.' => 'Every apartment in the tower you visit is carefully designed to meet family needs. Benefit from its proximity to convenient transportation stations, a Zoom Market, and a grocery store on the way. The spaces are spacious and offered at an affordable price, with a design that provides you with the utmost comfort and quality.',
];
